model_params:
  name: 'BetaVAE'
  num_bands: 162
  hidden_dims: [64,32]
  latent_dim: 2
  loss_type: 'B'
  gamma: 10.0
  max_capacity: 25
  Capacity_max_iter: 20000

exp_params:
  LR: 0.001
  weight_decay: 0.0
  KL_weight: 0.0003
  num_endmembers: 4

datamodule_params:
  data_path: "./data/Urban4.mat"
  threshold: 0.7
  batch_size: 256
  normalize: True

trainer_params:
  gpus: 0
  max_epochs: 60

logging_params:
  save_dir: "logs/"
  name: "BetaVAE"
  version: "1"
  manual_seed: 12345